## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
  - nightly
notifications:
  email: false

script: # the default script is equivalent to the following
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  # Uncomment the following lines to allow failures on nightly julia
  # (tests will run but not make your overall status red)
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
